version: '3.3'
services: 
    api:
        build: 
            dockerfile: Dockerfile
            context: .
        container_name: request-api
        image: request-api
        ports:
            - 3333:3333
        env_file: 
            ./.env
        depends_on: 
            - mongodb
    mongodb:
        image: 'mongo:4.4'
        container_name: mongodb
        ports: 
            - "27017:27017"